<h1>Assignment 1</h1>

<p>In this first assignment we are focusing on a classification problem.<br>
Our goal will be to use both the <b>K-Nearest Neighbors</b> and the <b>Decision Tree</b> techniques and try to compare the predictive models obtained.</p>

<h3>The Dataset</h3>
<p>For this assignment we will be using the sonar_train.csv data set</p>
<p>This data set contains signals obtained from a variety of different aspect angles, spanning 90 degrees for mines and 180 degrees for rocks. Each sample is a set of 60 numbers in the range 0.0 to 1.0, where each number represents the energy within a particular frequency band (integrated over a certain period of time). The output target contains the letter R if the object is a rock and M if it is a mine (metal cylinder).</p>

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [4]:
#Opening the sonar_train.csv file
data = pd.read_csv('sonar.csv')

###Display informations and the different column/features names


<p>In this data set each band is a feature and the target is the type of the object</p>
<h4> <u>QUESTION 1 :</u> How many samples and how many features do we have?</h4>
<p><i>There are 208 samples and 61 columns</i></p>

In [5]:
###using the train_test_split command split the data set in two : 'train' and 'test' with a ratio ~75%-25%
from sklearn.cross_validation import train_test_split
train, test = train_test_split(data)


In [6]:
#The last column in our sets correspond to the target
###Count how many of 'R' and 'M' you have in total

RInTrain = train[train['Type']=='R']
RInTest = test[test['Type']=='R']
MInTrain = train[train['Type']=='M']
MInTest = test[test['Type']=='M']
print 'There are: ',np.shape(RInTrain)[0] + np.shape(RInTest)[0], 'R and ', np.shape(MInTrain)[0] + np.shape(MInTest)[0], 'M in total'


There are:  97 R and  111 M in total


In [7]:
#In order to make targets more easily usable we will replace 'R' and 'M' by 0 and 1 respectively.
###Do it for both sets using the command: .replace()

new_train = train.replace("R", 0).replace('M',1)
new_test = test.replace("R", 0).replace('M',1)


In [8]:
training_data=new_train.drop(['Type'],axis=1).values

In [9]:
labels = new_train['Type'].values

<h3>K-Nearest Neighbors approach</h3>

<p>In this section we will apply the <b>K-Nearest Neighbors</b> technique to the data set</p>

In [10]:
from sklearn.neighbors import KNeighborsClassifier
###Fill the brackets to use the brute force approach and 7 neighbors
knn = KNeighborsClassifier(n_neighbors=7, algorithm='brute')

### Train the Nearest Neighbor Classifier "knn" on the training set
knn.fit(training_data, labels)

KNeighborsClassifier(algorithm='brute', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=7, p=2,
           weights='uniform')

<h4> <u>QUESTION 2 :</u> Which kind of impact has the choice of the algorithm?</h4>
<p><i>It has an impact on the computational time</i></p>

In [11]:
#At any time it is possible to recall the parameters using :
knn.get_params()

{'algorithm': 'brute',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': 1,
 'n_neighbors': 7,
 'p': 2,
 'weights': 'uniform'}

<p>We now want to test the accuracy of the nearest neighbor classifier</p>


In [12]:
###Compute the target prediction for the elements of the test set and compare with their true value
testing_data=new_test.drop(['Type'],axis=1).values
predictions = knn.predict(testing_data)
predictions

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0])

In [13]:
new_test['Type'].values

array([1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0])

In [14]:
#scikit actually includes an accuracy evaluation function :
###Compute the accuracy using knn.score()

knn.score(testing_data, new_test['Type'].values)

0.80769230769230771

<h4> <u>QUESTION 3 :</u> Is the accuracy acceptable?</h4>
<p><i>I think 80% accuracy is not good enough</i></p>

<p>In the following cell repeat the training and the test steps with different knn parameters and try to find a good combination.</p>

In [15]:
knn1 = KNeighborsClassifier(algorithm='brute', leaf_size=7, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

### Train the Nearest Neighbor Classifier "knn1" on the training set
knn1.fit(training_data, labels)

###Compute the target prediction for the elements of the test set and compare with their true value
testing_data=new_test.drop(['Type'],axis=1).values
predictions1 = knn1.predict(testing_data)
predictions1

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0])

In [16]:
###Compute the target prediction for the elements of the test set and compare with their true value
testing_data=new_test.drop(['Type'],axis=1).values
predictions1 = knn1.predict(testing_data)
predictions1

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0])

In [17]:
new_test['Type'].values

array([1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0])

In [18]:
knn1.score(testing_data, new_test['Type'].values)

0.73076923076923073

<h4> <u>QUESTION 4 :</u> What is the best accuracy you get? What can you conclude?</h4>
<p><i>86%. The parameters combination that gives 86% accuracy using Brute force algorithm is the same for other algorithms. Setting p=2 gives the maximum accuracy </i></p>

<h3>Decision Tree</h3>

<p>Using the same sets we now investigate the efficiency of a <b>decision tree classifier<b> </p>

In [19]:
from sklearn import tree
###
dtr = tree.DecisionTreeClassifier()

###train the decision tree classifier "dtr"
dtr.fit(training_data, labels)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [20]:
#Same as previously we can display some informations
dtr.get_params()

{'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'presort': False,
 'random_state': None,
 'splitter': 'best'}

<h4> <u>QUESTION 5 :</u> From the list above, give the keywords influencing the test performed at a decison node?</h4>
<p><i>criterion, max_depth, max_leaf_nodes</i></p>

<p>In the follwing, using the work done previously test the accuracy of the decision tree classifier.</p>

In [21]:
predictionsdtr = dtr.predict(testing_data)
predictionsdtr


array([1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0])

In [22]:
new_test['Type'].values

array([1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0])

In [23]:
dtr.score(testing_data, new_test['Type'].values)

0.78846153846153844

<p>Hereafter, using different parameters for our decision tree, try to improve the accuracy</p>

<h4> <u>QUESTION 6 :</u> Explain which parameter(s) you plan to change and why?</h4>
<p><i>Type your answer here</i></p>


In [24]:
dtr1 = tree.DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=7, min_samples_leaf=7,
            min_samples_split=3, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')
###train the decision tree classifier "dtr1"
dtr1.fit(training_data, labels)

predictionsdtr1 = dtr.predict(testing_data)
predictionsdtr1






array([1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0])

In [25]:
dtr1.score(testing_data, new_test['Type'].values)

0.78846153846153844

<p>The results are different but obviously when we identify mines we don't want to be wrong.</p>

<h4> <u>QUESTION 7 :</u> Which one of the two methods is better? Is the accuracy acceptable? Why?</h4>
<p><i>The Decision Tree method is better but the accuracy is not acceptable because it is not stable</i></p>

<h4> <u>QUESTION 8 :</u> What can you conclude from the whole study</h4>
<p><i>Type your answer here</i></p>


<h4> <u>BONUS :</u> Copy/Paste the code to generate a pdf file containing the best tree and attach the file generated to your assignment when sending everything to me</h4>

In [27]:
import pydot
from sklearn.externals.six import StringIO
dot_data = StringIO() 
f = tree.export_graphviz(dtr,out_file=dot_data, feature_names=None, class_names=None,filled=True, rounded=True) 
graph = pydot.graph_from_dot_data(dot_data.getvalue()) 
graph.write_pdf("dtr_decision_tree_assignment.pdf") 

True

In [28]:
import pydot
from sklearn.externals.six import StringIO
dot_data = StringIO() 
f = tree.export_graphviz(dtr1,out_file=dot_data, feature_names=None, class_names=None,filled=True, rounded=True) 
graph = pydot.graph_from_dot_data(dot_data.getvalue()) 
graph.write_pdf("dtr1_decision_tree_assignment.pdf") 

True